site_name: Помощник за Избори - 19 април 2026 г.
docs_dir: mkdocs_docs
site_dir: _site

nav:
  - Начало: README.md
  - Предизборен ден (18 април): "Предизборен ден.md"
  - Изборен ден (19 април): "Изборен ден.md"
  - Закриване на изборния ден: "Закриване на изборния ден.md"
  - Предаване на книжата и материалите на РИК: "Предаване на книжата и материалите на РИК.md"

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  language: bg
  palette:
    scheme: default
    primary: teal
palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Превключи към тъмен режим
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Превключи към светъл режим
