site_name: Помощник за Избори - 19 април 2026 г.
docs_dir: .
site_dir: _site

nav:
  - Начало: README.md
  - Предизборен ден (18 април): "Предизборен ден.md"
  - Изборен ден (19 април): "Изборен ден.md"
  - Закриване на изборния ден: "Закриване на изборния ден.md"
  - Предаване на книжата и материалите на РИК: "Предаване на книжата и материалите на РИК.md"

theme:
  name: material
  language: bg
  palette:
    scheme: default
    primary: blue
