site_name: Помощник за Изборите на 19 април 2026 г.
docs_dir: mkdocs_docs
site_dir: _site

hooks:
  - hooks.py

nav:
  - Начало: README.md
  - Предизборен ден (18 април): "Предизборен ден.md"
  - Изборен ден (19 април): "Изборен ден.md"
  - Броене: "Броене.md"
  - Предаване на книжата и материалите на РИК: "Предаване на книжата и материалите на РИК.md"
  - Длъжности в СИК: "Длъжности.md"
  - Подготовка на машината - СИЕЛА НОРМА: "Подготовка на машината.md"

extra_css:
  - extra.css

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  language: bg
  palette:
    scheme: default
    primary: indigo
palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Превключи към тъмен режим
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Превключи към светъл режим
